2025-05-24 18:38:04,838 - llm_entropy.analysis - INFO - Starting analysis run 20250524_183804_2576a2a1
2025-05-24 18:38:04,838 - llm_entropy.analysis - INFO - Loading models...
2025-05-24 18:38:05,827 - llm_entropy.analysis - INFO - Generating example sentences...
2025-05-24 18:38:05,860 - llm_entropy.analysis - ERROR - Analysis failed: 'functools.partial' object has no attribute '__name__'
Traceback (most recent call last):
  File "/Users/finchmf/coding/entropy/llm_entropy/main.py", line 124, in run_analysis
    gpt2_results.extend(future.result())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/finchmf/coding/entropy/llm_entropy/main.py", line 52, in process_batch
    if analysis_func.__name__ == 'bert_entropy_analysis':
AttributeError: 'functools.partial' object has no attribute '__name__'
